name: YariMoghadam
favicon: null
layout_spectrum: 0.2835808175150305
typography_spectrum: 0.6841629578266293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.29802615847438574
  lightness: 0.5341280370485038
  saturation: 0.3938033727463335
  rhythmicContrast: 0.7152168012689799
purpose: []
